export const en: Record<string, string> = {
  // Common
  financeTracker: 'Finance Tracker',
  welcomeMessage: 'Track your expenses easily',
  home: 'Home',
  credit: 'Credit',
  special: 'Special',
  summary: 'Summary',
  settings: 'Settings',
  
  // Home Screen
  quickActions: 'Quick Actions',
  addDailyExpense: 'Add Daily Expense',
  addCreditExpense: 'Add Credit Card Expense',
  addSpecialExpense: 'Add Special Expense',
  viewMonthlyReport: 'View Monthly Report',
  quickTip: 'Quick Tip',
  tipContent: 'Tap on any expense to see more details or edit it.',
  
  // Expenses Summary
  expensesSummary: 'Expenses Summary',
  today: 'Today',
  thisMonth: 'This Month',
  spent: 'Spent',
  remaining: 'Remaining',
  
  // Dashboard
  monthlySummary: 'Monthly Summary',
  monthlyOverview: 'Monthly Overview',
  dailyExpenses: 'Daily Expenses',
  creditExpenses: 'Credit Card Expenses',
  specialExpenses: 'Special Expenses',
  totalExpenses: 'Total Expenses',
  expenseBreakdown: 'Expense Breakdown',
  filter: 'Filter',
  export: 'Export',
  
  // Add Expense
  addExpense: 'Add Expense',
  dateAndTime: 'Date and Time',
  date: 'Date',
  time: 'Time',
  month: 'Month',
  day: 'Day',
  year: 'Year',
  hour: 'Hour',
  minute: 'Minute',
  ampm: 'AM/PM',
  amount: 'Amount',
  purpose: 'Purpose',
  enterPurpose: 'Enter purpose...',
  paymentMethod: 'Payment Method',
  cash: 'Cash',
  upi: 'UPI',
  card: 'Card',
  notes: 'Notes',
  enterNotes: 'Enter notes...',
  remindMeLater: 'Remind Me Later',
  saveExpense: 'Save Expense',
  cancel: 'Cancel',
  save: 'Save',
  
  // Settings
  preferences: 'Preferences',
  language: 'Language',
  darkMode: 'Dark Mode',
  dataManagement: 'Data Management',
  exportData: 'Export Data',
  exportDataDescription: 'Choose the format to export your expenses data',
  shareApp: 'Share App',
  clearAllData: 'Clear All Data',
  clearDataWarning: 'This will permanently delete all your expense data. This action cannot be undone.',
  clearData: 'Clear Data',
  helpAndSupport: 'Help & Support',
  support: 'Support',
};