export const ta: Record<string, string> = {
  // Common
  financeTracker: 'நிதி கண்காணிப்பு',
  welcomeMessage: 'உங்கள் செலவுகளை எளிதாக கண்காணிக்கவும்',
  home: 'முகப்பு',
  credit: 'கடன்',
  special: 'சிறப்பு',
  summary: 'சுருக்கம்',
  settings: 'அமைப்புகள்',
  
  // Home Screen
  quickActions: 'விரைவு செயல்கள்',
  addDailyExpense: 'தினசரி செலவைச் சேர்க்கவும்',
  addCreditExpense: 'கடன் அட்டை செலவைச் சேர்க்கவும்',
  addSpecialExpense: 'சிறப்பு செலவைச் சேர்க்கவும்',
  viewMonthlyReport: 'மாதாந்திர அறிக்கையைக் காண்க',
  quickTip: 'விரைவு குறிப்பு',
  tipContent: 'மேலும் விவரங்களைப் பார்க்க அல்லது திருத்த எந்த செலவிலும் தட்டவும்.',
  
  // Expenses Summary
  expensesSummary: 'செலவுகள் சுருக்கம்',
  today: 'இன்று',
  thisMonth: 'இந்த மாதம்',
  spent: 'செலவழித்தது',
  remaining: 'மீதமுள்ள',
  
  // Dashboard
  monthlySummary: 'மாதாந்திர சுருக்கம்',
  monthlyOverview: 'மாதாந்திர கண்ணோட்டம்',
  dailyExpenses: 'தினசரி செலவுகள்',
  creditExpenses: 'கடன் அட்டை செலவுகள்',
  specialExpenses: 'சிறப்பு செலவுகள்',
  totalExpenses: 'மொத்த செலவுகள்',
  expenseBreakdown: 'செலவு பகுப்பாய்வு',
  filter: 'வடிகட்டி',
  export: 'ஏற்றுமதி',
  
  // Add Expense
  addExpense: 'செலவு சேர்க்க',
  dateAndTime: 'தேதி மற்றும் நேரம்',
  date: 'தேதி',
  time: 'நேரம்',
  month: 'மாதம்',
  day: 'நாள்',
  year: 'ஆண்டு',
  hour: 'மணி',
  minute: 'நிமிடம்',
  ampm: 'AM/PM',
  amount: 'தொகை',
  purpose: 'நோக்கம்',
  enterPurpose: 'நோக்கத்தை உள்ளிடவும்...',
  paymentMethod: 'கட்டண முறை',
  cash: 'பணம்',
  upi: 'UPI',
  card: 'அட்டை',
  notes: 'குறிப்புகள்',
  enterNotes: 'குறிப்புகளை உள்ளிடவும்...',
  remindMeLater: 'பின்னர் நினைவூட்டவும்',
  saveExpense: 'செலவை சேமிக்கவும்',
  cancel: 'ரத்து செய்',
  save: 'சேமி',
  
  // Settings
  preferences: 'விருப்பங்கள்',
  language: 'மொழி',
  darkMode: 'இருண்ட பயன்முறை',
  dataManagement: 'தரவு மேலாண்மை',
  exportData: 'தரவை ஏற்றுமதி செய்',
  exportDataDescription: 'உங்கள் செலவு தரவை ஏற்றுமதி செய்ய வடிவத்தைத் தேர்ந்தெடுக்கவும்',
  shareApp: 'பயன்பாட்டைப் பகிரவும்',
  clearAllData: 'அனைத்து தரவையும் அழிக்கவும்',
  clearDataWarning: 'இது உங்கள் அனைத்து செலவு தரவையும் நிரந்தரமாக நீக்கும். இந்த செயலை செயல்தவிர்க்க முடியாது.',
  clearData: 'தரவை அழிக்கவும்',
  helpAndSupport: 'உதவி & ஆதரவு',
  support: 'ஆதரவு',
};